### ISSUE TITLE
[HOTFIX] 회원가입 validation 체크 버그

### ISSUE THREAD

**Issue by CokeLee777** [lotte-bit-1/shopping-mall-servlet-jsp#130]
1. 검증 오류 메시지는 올바른데 input 박스가 초록불이 들어옴
![스크린샷 2023-08-29 오후 11 45 32](https://github.com/lotte-bit-1/shopping-mall-servlet-jsp/assets/64250896/cd37db3e-c6ea-480b-907d-a29f6f5bcabe)

2. 이메일 형식이 아닌데 사용할 수 있는 아이디라고 검증
-> submit 시에는 백엔드단에서는 검증되는 것으로 확인
![스크린샷 2023-08-29 오후 11 45 19](https://github.com/lotte-bit-1/shopping-mall-servlet-jsp/assets/64250896/55f01c45-23e0-4910-84fa-36140e1834df)

**Comment by sjy4974** [comment]
확인
